assignment3:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 34.233.79.135
      port: 5432
      user: postgres
      password: Afraz13252@
      dbname: postgres
      schema: silver
      threads: 4
      keepalives_idle: 0
